src/Entity/Etape.php
<?php

namespace App\Entity;

use App\Repository\EtapeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EtapeRepository::class)]
class Etape
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $texte_ambiance = null;

    #[ORM\Column(length: 255)]
    private ?string $libelle = null;

    #[ORM\OneToOne(mappedBy: 'premiereEtape', cascade: ['persist', 'remove'])]
    private ?Aventure $aventureDeButee = null;

    #[ORM\ManyToOne(inversedBy: 'etapes')]
    private ?Aventure $aventure = null;

    #[ORM\ManyToOne(inversedBy: 'finsPossibles')]
    private ?Aventure $finAventure = null;

    /**
     * @var Collection<int, Partie>
     */
    #[ORM\OneToMany(targetEntity: Partie::class, mappedBy: 'etape')]
    private Collection $parties;

    /**
     * @var Collection<int, Alternative>
     */
    #[ORM\OneToMany(targetEntity: Alternative::class, mappedBy: 'etapePrecedente')]
    private Collection $alternatives;

    public function __construct()
    {
        $this->parties = new ArrayCollection();
        $this->alternatives = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTexteAmbiance(): ?string
    {
        return $this->texte_ambiance;
    }

    public function setTexteAmbiance(string $texte_ambiance): static
    {
        $this->texte_ambiance = $texte_ambiance;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): static
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getAventureDeButee(): ?Aventure
    {
        return $this->aventureDeButee;
    }

    public function setAventureDeButee(?Aventure $aventureDeButee): static
    {
        // unset the owning side of the relation if necessary
        if ($aventureDeButee === null && $this->aventureDeButee !== null) {
            $this->aventureDeButee->setPremiereEtape(null);
        }

        // set the owning side of the relation if necessary
        if ($aventureDeButee !== null && $aventureDeButee->getPremiereEtape() !== $this) {
            $aventureDeButee->setPremiereEtape($this);
        }

        $this->aventureDeButee = $aventureDeButee;

        return $this;
    }

    public function getAventure(): ?Aventure
    {
        return $this->aventure;
    }

    public function setAventure(?Aventure $aventure): static
    {
        $this->aventure = $aventure;

        return $this;
    }

    public function getFinAventure(): ?Aventure
    {
        return $this->finAventure;
    }

    public function setFinAventure(?Aventure $finAventure): static
    {
        $this->finAventure = $finAventure;

        return $this;
    }

    /**
     * @return Collection<int, Partie>
     */
    public function getParties(): Collection
    {
        return $this->parties;
    }

    public function addParty(Partie $party): static
    {
        if (!$this->parties->contains($party)) {
            $this->parties->add($party);
            $party->setEtape($this);
        }

        return $this;
    }

    public function removeParty(Partie $party): static
    {
        if ($this->parties->removeElement($party)) {
            // set the owning side to null (unless already changed)
            if ($party->getEtape() === $this) {
                $party->setEtape(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->libelle;
    }

    /**
     * @return Collection<int, Alternative>
     */
    public function getAlternatives(): Collection
    {
        return $this->alternatives;
    }

    public function addAlternative(Alternative $alternative): static
    {
        if (!$this->alternatives->contains($alternative)) {
            $this->alternatives->add($alternative);
            $alternative->setEtapePrecedente($this);
        }

        return $this;
    }

    public function removeAlternative(Alternative $alternative): static
    {
        if ($this->alternatives->removeElement($alternative)) {
            // set the owning side to null (unless already changed)
            if ($alternative->getEtapePrecedente() === $this) {
                $alternative->setEtapePrecedente(null);
            }
        }

        return $this;
    }
}

src/Controller/JouerController.php
<?php
namespace App\Entity;
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\PersonnageRepository;
use App\Repository\AventureRepository;
use App\Repository\EtapeRepository;
use App\Form\PersonnageType;
use App\Entity\Personnage;
use App\Entity\Aventure;
use App\Entity\Etape;
use App\Entity\Partie;
use App\Repository\PartieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;

class JouerController extends AbstractController
{
    #[Route('/jouer', name: 'app_jouer')]
    public function index(PersonnageRepository $personnageRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $user = $this->getUser();
        $personnages = $personnageRepository->findBy(["user" => $user]);

        return $this->render('jouer/index.html.twig', [
            'personnages' => $personnages,
        ]);
    }

    #[Route('/jouer/new', name: 'app_jouer_new')]
    public function newPersonnage(Request $request, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $personnage = new Personnage();
        $form = $this->createForm(PersonnageType::class, $personnage);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $personnage->setUser($this->getUser());
            $entityManager->persist($personnage);
            $entityManager->flush();
            return $this->redirectToRoute('app_jouer', [], Response::HTTP_SEE_OTHER);
        }
        return $this->render('jouer/new_personnage.html.twig', ['form' => $form, 'personnage' => $personnage]);
    }

    #[Route('/jouer/aventures/{idPersonnage}', name: 'app_choix_aventure', methods: ['GET'])]
    public function afficherAventures(AventureRepository $aventureRepository, PersonnageRepository $personnageRepository, $idPersonnage): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $personnage = $personnageRepository->find($idPersonnage);
        if (!$personnage) {
            throw $this->createNotFoundException('Le personnage n\'existe pas.');
        }
        $aventures = $aventureRepository->findAll();
        return $this->render('jouer/aventures.html.twig', ['aventures' => $aventures, 'personnage' => $personnage]);
    }

    #[Route('/jouer/aventure/{idPersonnage}/{idAventure}', name: 'app_start_aventure', methods: ['GET'])]
    public function demarrerAventure(PersonnageRepository $personnageRepository, AventureRepository $aventureRepository, PartieRepository $partieRepository, $idPersonnage, $idAventure, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $personnage = $personnageRepository->find($idPersonnage);
        $aventure = $aventureRepository->find($idAventure);

        if (!$personnage || !$aventure) {
            throw $this->createNotFoundException('Le personnage ou l\'aventure n\'existe pas.');
        }

        $partie = $partieRepository->findOneBy(['aventurier' => $personnage, 'aventure' => $aventure]);
        $isNewPartie = !isset($partie);

        if ($isNewPartie) {
            $partie = new Partie();
            $partie->setAventurier($personnage);
            $partie->setAventure($aventure);
            $partie->setEtape($aventure->getPremiereEtape());
            $partie->setDatePartie(new \DateTime('now'));
            $entityManager->persist($partie);
            $entityManager->flush();
        }

        return $this->render('jouer/aventure-start.html.twig', [
            'personnage' => $personnage,
            'aventure' => $aventure,
            'isNewPartie' => $isNewPartie,
            'partie' => $partie,
        ]);
    }

    #[Route('/jouer/etape/{idPartie}/{idEtape}', name: 'app_play_etape', methods: ['GET'])]
    public function jouerEtape(PartieRepository $partieRepository, EtapeRepository $etapeRepository, EntityManagerInterface $entityManager, $idPartie, $idEtape): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        
        $partie = $partieRepository->find($idPartie);
        if (!$partie) {
            throw $this->createNotFoundException('La partie n\'existe pas.');
        }

        $etape = $etapeRepository->find($idEtape);
        if (!$etape) {
            throw $this->createNotFoundException('L\'étape n\'existe pas.');
        }

        $partie->setEtape($etape);
        $entityManager->persist($partie);
        $entityManager->flush();

        return $this->render('jouer/aventure-etape.html.twig', [
            'partie' => $partie,
            'etape' => $etape,
        ]);
    }

    #[Route('/jouer/alternative/{idPartie}/{idEtape}/{idAlternative}', name: 'app_play_alternative', methods: ['GET'])]
    public function jouerAlternative(PartieRepository $partieRepository, EtapeRepository $etapeRepository, EntityManagerInterface $entityManager, $idPartie, $idEtape, $idAlternative): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $partie = $partieRepository->find($idPartie);
        if (!$partie) {
            throw $this->createNotFoundException('La partie n\'existe pas.');
        }

        $etape = $etapeRepository->find($idEtape);
        if (!$etape) {
            throw $this->createNotFoundException('L\'étape n\'existe pas.');
        }

        // Logique pour récupérer et appliquer l'alternative choisie.
        $alternative = $etape->getAlternatives()->filter(function ($alt) use ($idAlternative) {
            return $alt->getId() == $idAlternative;
        })->first();

        if (!$alternative) {
            throw $this->createNotFoundException('L\'alternative n\'existe pas.');
        }

        $nextEtape = $alternative->getNextEtape();
        $partie->setEtape($nextEtape);
        $entityManager->persist($partie);
        $entityManager->flush();

        return $this->redirectToRoute('app_play_etape', [
            'idPartie' => $idPartie,
            'idEtape' => $nextEtape->getId()
        ]);
    }
}

templates/jouer/aventure-end.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fin de l'aventure{% endblock %}

{% block body %}

<style>
  .container h1 {background-color: white;font-weight: bold}
    p{background-color: white; text-align:center}
</style>

<div class="container mt-5">
    <h1 class="text-center">{{ etape.libelle }}</h1>
    <p>{{ etape.texteAmbiance }}</p>
    <div class="text-center mt-4">
        <a href="{{ path('app_jouer') }}" class="btn btn-primary">Retourner à la sélection des aventures</a>
    </div>
    <div class="text-center mt-4">
        <p>Félicitations ! Vous avez terminé l'aventure. Vous avez assuré !</p>
    </div>
</div>
{% endblock %}

templates/jouer/aventure-etape.html.twig
{% extends 'base.html.twig' %}

{% block title %}Jouer Étape{% endblock %}

{% block body %}
<div class="container mt-5">
    <div class="card">
        <div class="card-body">
            <h1 class="card-title">{{ etape.id }}</h1>
            <p class="card-text">{{ etape.texteAmbiance }}</p>

            {% if etape.alternatives is not empty %}
                <h2 class="mt-4">Choisissez une alternative :</h2>
                <ul class="list-group">
                {% for alternative in etape.alternatives %}
                    <li class="list-group-item">
                        <a href="{{ path('app_play_alternative', { 'idPartie': partie.id, 'idEtape': etape.id, 'idAlternative': alternative.id }) }}">
                            {{ alternative.texteAmbiance }}
                        </a>
                    </li>
                {% endfor %}
                </ul>
            {% else %}
                <p class="mt-4">Fin de l'aventure. Félicitations !</p>
            {% endif %}

            <!-- Bouton pour revenir au début -->
            <div class="mt-4">
                <a href="{{ path('app_jouer') }}" class="btn btn-secondary">Revenir au début</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/jouer/aventure-play.html.twig
{% extends 'base.html.twig' %}

{% block title %}Jouer l'étape{% endblock %}

{% block body %}

<style>
    .container {background-color: white;font-weight: bold}
</style>

<div class="container mt-5">
    <h1 class="text-center">{{ partie.etape.titre }}</h1>
    <p>{{ partie.etape.texteAmbiance }}</p>
    <div class="mt-4">
        {% for alternative in partie.etape.alternatives %}
            <div class="mb-2">
                <a href="{{ path('app_play_aventure', {'idPartie': partie.id, 'idEtape': alternative.id }) }}" class="btn btn-secondary w-100">
                    {{ alternative.texteAmbiance }}
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/jouer/aventure-start.html.twig
{% extends 'base.html.twig' %}

{% block title %}Démarrer Aventure{% endblock %}

{% block body %}
<div class="container mt-5">
    <div class="card shadow-lg">
        <div class="card-header bg-primary text-white text-center">
            <h1>Démarrer Aventure</h1>
        </div>
        <div class="card-body">
            <p><strong>Personnage:</strong> {{ personnage.prenom }} {{ personnage.nom }}</p>
            <p><strong>Aventure ID:</strong> {{ aventure.id }}</p>

            {% if isNewPartie %}
                <div class="alert alert-success text-center">
                    <p>Une nouvelle partie a été créée.</p>
                </div>
            {% else %}
                <div class="alert alert-info text-center">
                    <p>Reprise de la partie en cours.</p>
                </div>
            {% endif %}

            <div class="text-center mt-4">
                <a href="{{ path('app_play_etape', {'idPartie': partie.id, 'idEtape': partie.etape.id}) }}" class="btn btn-primary btn-lg">Lancer</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/jouer/aventures.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des aventures{% endblock %}

{% block body %}
<style>
    a { width: 200px; }
</style>

<div id="enligne" class="d-flex flex-row justify-content-around align-items-center">
    <div class="card" class="p-2" style="width: 18rem;">
        <img src="{{ asset('images/avatars/' ~ personnage.avatar.getNomFichier(personnage.id)) }}">
        <div class="card-body">
            <h5 class="card-title">Vous avez sélectionné le personnage : {{ personnage.prenom }} {{ personnage.nom }}</h5>
        </div>
    </div>
    {% for aventure in aventures %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ aventure.titre }}</h5>
            <p>{{aventure.description}}</p>
            <a href="{{ path('app_start_aventure', {'idPersonnage': personnage.id, 'idAventure': aventure.id }) }}" class="btn btn-primary btn-lg">Jouer</a>
        </div>
    </div>
    {% else %}
    Aucune aventure
    {% endfor %}
</div> 
<h1>Liste des aventures</h1>   
{% endblock %}

templates/jouer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello JouerController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    .row { background-color: white; }
</style>

<div class="example-wrapper">
</div>

<div class="col">
    <div class="row p-3 mb-2 bg-white">
        {% for personnage in personnages %}
        <div class="card col-6 mx-auto" style="width: 17rem">
            <img src="{{ asset('images/avatars/' ~ personnage.avatar.getNomFichier()) }}">
            <div class="card-body col-6 mx-auto">
                <h1>{{ personnage.id }}</h1>
                <h5 class="card-title">
                    <a href="{{ path('app_choix_aventure', { 'idPersonnage': personnage.id }) }}" class="btn btn-primary btn-lg">
                        {{ personnage.prenom }} {{ personnage.nom }}
                    </a>
                </h5>
            </div>
        </div>
        {% else %}
        <p>Aucun personnage trouvé.</p>
        {% endfor %}
    </div>

    <div class="col d-flex justify-content-end">
        <a href="{{ path('app_jouer_new') }}" class="btn btn-success">Créer</a>
    </div>
</div>

{% endblock %}

templates/jouer/new_personnage.html.twig
{% extends 'base.html.twig' %}
{% block title %}Creer un nouveau personnage{% endblock %}
{% block body %}
<style> 
        form{ display: flex; flex-direction: column}
        form button{display: flex;flex-direction: row; width:100px }
        #personnage{background-color:white; padding: 10px}
		.button {display: flex; justify-content:flex-end;}
</style>
	{{ form_start(form) }}
	{{ form_widget(form) }}
	<div class="button"><button>Créer</button></div>

	{{ form_end(form) }}
<h1>Creer un nouveau personnage</h1> 
{% endblock %}